## SERVICES ##
# Supported values: hipchat, campfire, hipchat-smackr
service: hipchat

## HIPCHAT SETTINGS ##
hipchat:
  jid: <%= ENV['HIPCHAT_JID'] %>
  name: <%= ENV['HIPCHAT_NAME'] %>
  password: <%= ENV['HIPCHAT_PASSWORD'] %>
  history: 0 # num of history fields to request
  rooms:
    - <%= ENV['HIPCHAT_ROOM'] %>

## BOT SETTINGS ##
# hello/goodbye messages can either be the name of a plugin, or a string
# the plugin must be enabled, and not all plugins support this type of message
bot:
  hello: 'All Aboard!'

## PLUGIN SETTINGS ##
enabled_plugins:
  - Isepta
